enableGlobalCache: false

pnpEnableEsmLoader: true

packageExtensions:
  '@mikro-orm/cli@*':
    peerDependencies:
      '@mikro-orm/knex': '*'
      '@mikro-orm/core': '*'
  '@mikro-orm/postgresql@*':
    peerDependencies:
      '@mikro-orm/knex': '*'
  '@mikro-orm/migrations@*':
    peerDependencies:
      '@mikro-orm/knex': '*'
  '@mikro-orm/entity-generator@*':
    peerDependencies:
      '@mikro-orm/knex': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      ioredis: '*'
      kafkajs: '*'
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'
  '@monstrs/protobuf-rpc@*':
    dependencies:
      '@bufbuild/protobuf': '*'
  '@socket.io/redis-streams-adapter@*':
    dependencies:
      'socket.io-adapter': '*'
      'redis': '*'
  knex@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
      tedious: '*'
  next@*:
    dependencies:
      buffer: '*'

yarnPath: .yarn/releases/yarn-remote.cjs
